[package]
name = "pog_os"
version = "0.1.0"
edition = "2021"
authors = ["WorksByM <wittki56@gmail.com>"]

[build-dependencies]
bootloader = "0.11.7"
kernel = { path = "kernel", artifact = "bin", target = "x86_64-unknown-none" }


[workspace]
members = ["kernel"]