[package]
name = "kernel"
version = "0.1.0"
edition = "2021"
authors = ["WorksByM <wittki56@gmail.com>"]

[dependencies]
bootloader_api = "0.11.4"
noto-sans-mono-bitmap = "0.2.0"
volatile = "0.5.1"
x86_64 = "0.14.10"
