name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Add kernel target
      run: rustup target add x86_64-unknown-none
    - name: Add build target
      run: rustup target add nightly-x86_64-unknown-linux-gnu
    - name: Add nightly rust-src
      run: rustup component add rust-src --toolchain nightly-x86_64-unknown-linux-gnu
    - name: Add rustup llvm component
      run: rustup component add llvm-tools-preview
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose -Zbindeps -Zbuild-std --target x86_64-unknown-none
