name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Add and switch to Nightly channel
      run: rustup toolchain install nightly && rustup default nightly
    - name: Add targets
      run: rustup target add x86_64-unknown-none && rustup target add x86_64-unknown-linux-gnu
    - name: Add nightly rust-src
      run: rustup component add rust-src --toolchain nightly-x86_64-unknown-linux-gnu
    - name: Add rustup llvm component
      run: rustup component add llvm-tools-preview
    - uses: actions/checkout@v3
    - name: Build
      run: cargo run --verbose
    - name: Publish
      uses: actions/upload-artifact@v4
      with:
        name: boot-imgs
        path: |
          ${{ env.UEFI_PATH }}
          ${{ env.BIOS_PATH }}